### ISSUE TITLE
Can't get the theme to apply

### ISSUE THREAD

**Issue by CitizenFoffie** [florinsdistortedvision/rinfox_updated#4]
I followed all the steps but after I cleared my startup cache nothing applied

**Comment by florinsdistortedvision** [comment]
Please provide more info. This applies fine if you're using firefox 115. ffroot's contents in firefox's folder and chrome (with folder) in your profile will apply it.

**Comment by CitizenFoffie** [comment]
I did the install process for 115, all though it is possible that it hasn't downgraded, is theree a way I can check what version its using?

**Comment by florinsdistortedvision** [comment]
In about:support version should match with these:
Name 	Firefox
Version 	115.3.1esr

**Comment by CitizenFoffie** [comment]
It matches, I have 115.3.1esr

**Comment by florinsdistortedvision** [comment]
If you can't get theme to apply it means you haven't followed the steps correctly, please try again. The theme works fine

**Comment by CitizenFoffie** [comment]
I've repeated every step 3 times over at this point, when I go to clear my startup cache and reset it never applies
